//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "node")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub relay: bool,
    pub name: String,
    pub public_key: Option<String>,
    pub private_key: Option<String>,
    pub listen_port: Option<u16>,
    pub allowed_ips: Option<String>,
    pub endpoint_allowed_ips: Option<String>,
    pub persistent_keepalive: Option<String>,
    pub endpoint: Option<String>,
    pub mtu: Option<u32>,
    pub pre_up: Option<String>,
    pub post_up: Option<String>,
    pub pre_down: Option<String>,
    pub post_down: Option<String>
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
